FROM golang:1.25 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/payment-service ./cmd/main.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app

COPY --from=builder /bin/payment-service /app/payment-service
COPY --from=builder /app/migrations /app/migrations

EXPOSE 8081 9091
ENTRYPOINT ["/app/payment-service"]
